# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
builds:
  - targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_386
      - windows_amd64
archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*

release:
  github:
    owner: p0bailey
    name: tofuinit
snapshot:
  name_template: "{{ .Tag }}-dev"

universal_binaries:
  - replace: true

brews:
  - name: tofuinit
    homepage: https://github.com/p0bailey/tofuinit
    repository:
      owner: p0bailey
      name: homebrew-tools
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: p0bailey
      email: phillip.albert.bailey.@gmail.com
